# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4d2f7bb07af9d6759cabbb44dcd36d9bbdfe22ef72d60eeb87233a9cb009e27e2b09d4166bf715ab33bfd7801e00f480a1254518a4e7982a263812163b69400

test:
  secret_key_base: f43c08b5e5a095f38bfbcceca27e87a767ac35e9001053c79a56cf13ee6881e24a369d8d85234ddefdbacc4f6160dc4547ed55f5a4bd3062c349a1ff9af88c16

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
